# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
add_files /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/counter.bd
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_dlmb_v10_0/counter_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_dlmb_v10_0/counter_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_ilmb_v10_0/counter_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_ilmb_v10_0/counter_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_dlmb_bram_if_cntlr_0/counter_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_ilmb_bram_if_cntlr_0/counter_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_lmb_bram_0/counter_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_xbar_0/counter_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/counter_ooc.xdc]
set_property is_locked true [get_files /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/counter.bd]

read_verilog -library xil_defaultlib /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/sources_1/bd/counter/hdl/counter_wrapper.v
read_xdc /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/constrs_1/new/up_down_counter.xdc
set_property used_in_implementation false [get_files /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab2/project_2/project_2.srcs/constrs_1/new/up_down_counter.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top counter_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef counter_wrapper.dcp
catch { report_utilization -file counter_wrapper_utilization_synth.rpt -pb counter_wrapper_utilization_synth.pb }
