# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/up_down_counter.xdc

# Block Designs: bd/counter/counter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter || ORIG_REF_NAME==counter}]

# IP: bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_microblaze_0_0 || ORIG_REF_NAME==counter_microblaze_0_0}]

# IP: bd/counter/ip/counter_dlmb_v10_0/counter_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_dlmb_v10_0 || ORIG_REF_NAME==counter_dlmb_v10_0}]

# IP: bd/counter/ip/counter_ilmb_v10_0/counter_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_ilmb_v10_0 || ORIG_REF_NAME==counter_ilmb_v10_0}]

# IP: bd/counter/ip/counter_dlmb_bram_if_cntlr_0/counter_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==counter_dlmb_bram_if_cntlr_0}]

# IP: bd/counter/ip/counter_ilmb_bram_if_cntlr_0/counter_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==counter_ilmb_bram_if_cntlr_0}]

# IP: bd/counter/ip/counter_lmb_bram_0/counter_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_lmb_bram_0 || ORIG_REF_NAME==counter_lmb_bram_0}]

# IP: bd/counter/ip/counter_microblaze_0_axi_periph_0/counter_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_microblaze_0_axi_periph_0 || ORIG_REF_NAME==counter_microblaze_0_axi_periph_0}]

# IP: bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_mdm_1_0 || ORIG_REF_NAME==counter_mdm_1_0}]

# IP: bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_clk_wiz_1_0 || ORIG_REF_NAME==counter_clk_wiz_1_0}]

# IP: bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==counter_rst_clk_wiz_1_100M_0}]

# IP: bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_axi_gpio_0_0 || ORIG_REF_NAME==counter_axi_gpio_0_0}]

# IP: bd/counter/ip/counter_xbar_0/counter_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_xbar_0 || ORIG_REF_NAME==counter_xbar_0}]

# IP: bd/counter/ip/counter_xlconstant_0_0/counter_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_xlconstant_0_0 || ORIG_REF_NAME==counter_xlconstant_0_0}]

# IP: bd/counter/ip/counter_VDD_0/counter_VDD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_VDD_0 || ORIG_REF_NAME==counter_VDD_0}]

# IP: bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_axi_gpio_0_1 || ORIG_REF_NAME==counter_axi_gpio_0_1}]

# XDC: bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_microblaze_0_0 || ORIG_REF_NAME==counter_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0_ooc_debug.xdc

# XDC: bd/counter/ip/counter_microblaze_0_0/counter_microblaze_0_0_ooc.xdc

# XDC: bd/counter/ip/counter_dlmb_v10_0/counter_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_dlmb_v10_0 || ORIG_REF_NAME==counter_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_dlmb_v10_0/counter_dlmb_v10_0_ooc.xdc

# XDC: bd/counter/ip/counter_ilmb_v10_0/counter_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_ilmb_v10_0 || ORIG_REF_NAME==counter_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_ilmb_v10_0/counter_ilmb_v10_0_ooc.xdc

# XDC: bd/counter/ip/counter_dlmb_bram_if_cntlr_0/counter_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/counter/ip/counter_ilmb_bram_if_cntlr_0/counter_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/counter/ip/counter_lmb_bram_0/counter_lmb_bram_0_ooc.xdc

# XDC: bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_mdm_1_0 || ORIG_REF_NAME==counter_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0_ooc_trace.xdc

# XDC: bd/counter/ip/counter_mdm_1_0/counter_mdm_1_0_ooc.xdc

# XDC: bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_clk_wiz_1_0 || ORIG_REF_NAME==counter_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_clk_wiz_1_0 || ORIG_REF_NAME==counter_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/counter/ip/counter_clk_wiz_1_0/counter_clk_wiz_1_0_ooc.xdc

# XDC: bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==counter_rst_clk_wiz_1_100M_0}]

# XDC: bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==counter_rst_clk_wiz_1_100M_0}]

# XDC: bd/counter/ip/counter_rst_clk_wiz_1_100M_0/counter_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_axi_gpio_0_0 || ORIG_REF_NAME==counter_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0_ooc.xdc

# XDC: bd/counter/ip/counter_axi_gpio_0_0/counter_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_axi_gpio_0_0 || ORIG_REF_NAME==counter_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_xbar_0/counter_xbar_0_ooc.xdc

# XDC: bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_axi_gpio_0_1 || ORIG_REF_NAME==counter_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1_ooc.xdc

# XDC: bd/counter/ip/counter_axi_gpio_0_1/counter_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==counter_axi_gpio_0_1 || ORIG_REF_NAME==counter_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/counter/counter_ooc.xdc
