
obj-m += hello.o multiply.o multiplier.o

all:
	#make -C /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab4/linux-3.14 M=$(PWD)	modules
	make -C /home/dweerasinghe/Documents/ECEN_449/Labwork/Lab4/linux-3.14 M=$(PWD) modules

clean:
	#make -C /home/ugrads/d/dweerasinghe/ECEN449/Labwork/Lab4/linux-3.14 M=$(PWD)	clean
	make -C /home/dweerasinghe/Documents/ECEN_449/Labwork/Lab4/linux-3.14 M=$(PWD) clean


